---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: bggapp-po
      dept: dev
  template: 
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
        dept: dev
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: myapp-config
        - secretRef:
            name: myapp-secret
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  type: LoadBalancer
  selector: 
    name: bggapp-po
    dept: dev
  ports:
  - port: 80
    targetPort: 3000