---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: bggns
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: bggns
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: bggapp-po
      dept: dev
  template: 
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
        dept: dev
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_USER
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: BGG_DB_USER
        - name: BGG_DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: myapp-config
              key: BGG_DB_HOST
        - name: BGG_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: myapp-secret
              key: BGG_DB_PASSWORD
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
  namespace: bggns
spec:
  type: ClusterIP
  selector: 
    name: bggapp-po
    dept: dev
  ports:
  - port: 3000
    targetPort: 3000