---
apiVersion: v1 
kind: Service
metadata:
  name: mio-hsvc 
  labels:
    name: mio-hsvc 
  namespace: mions
spec: 
  clusterIP: None 
  selector:
    name: mio-po
  ports:
  - name: mio-data
    port: 9000
    targetPort: 9000
  - name: mio-console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: mio-sts
  labels:
    name: mio-sts
  namespace: mions
spec:
  serviceName: mio-hsvc
  replicas: 4
  selector:
    matchLabels:
      name: mio-po
  volumeClaimTemplates: 
  - apiVersion: v1 
    kind: PersistentVolumeClaim
    metadata: 
      name: data-vol
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: mio-po
      labels:
        name: mio-po
    spec:
      initContainers:
      - name: mio-init-container
        image: busybox
        command:
        - /bin/sh
        - -c 
        - "chown 1001 /data"
        volumeMounts:
          - name: data-vol
            mountPath: /data
      containers:
      - name: mio-container
        image: bitnami/minio:2022.12.12
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://mio-sts-{0...3}.mio-hsvc.mions.svc.cluster.local/data
        envFrom:
        - secretRef:
            name: minio-secret
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/live
            port: 9000
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /minio/health/ready
            port: 9000
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
        volumeMounts:
        - name: data-vol
          mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: mio-svc
  labels:
    name: mio-svc
  namespace: mions
spec:
  type: ClusterIP
  selector:
    name: mio-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: mio-ing
  labels:
    name: mio-ing
  namespace: mions
  annotations: 
    nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  ingressClassName: nginx
  rules:
  - host: data-146.190.202.83.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: mio-svc
            port: 
              name: data
  - host: console-146.190.202.83.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: mio-svc
            port: 
              name: console
          